Issue 34
devhatt/octopost-backend pull request #124
Opened 2024-06-13 22:55 UTC by thiagoCalazans-dev

Closes #34 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Feat Auth Login Service

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-06-14 14:27 UTC, hxsggsz requested changes

2024-06-14 14:27 UTC, hxsggsz commented on src/features/auth/services/auth-login-service.ts
> +      throw new Error('Invalid Credentials!');
cria um custom error igual tem na pasta `src/shared/errors` e bota aqui

2024-06-17 16:53 UTC, kvnbg approved these changes

2024-06-18 19:38 UTC, hxsggsz approved these changes

2024-06-19 15:21 UTC, merged