Issue 28
devhatt/octopost-backend pull request #130
Opened 2024-06-20 13:19 UTC by matheus-webp

Closes #28 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

[Email] - Implementação de envio de email para o modulo de usuário

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [X] Issue linked
- [X] Build working correctly
- [X] Tests created
</details>

2024-06-21 12:07 UTC, hxsggsz requested changes

2024-06-21 12:07 UTC, hxsggsz commented on src/shared/errors/error.test.ts
> +    it('parses to json correctly', () => {
faltou ajustar o titulo desse it

2024-06-21 12:07 UTC, hxsggsz commented on src/shared/infra/email/models/email-model.ts
> +  [key: string]: unknown;
tipar um objeto assim funciona mas eu nao sou muito fã de fazer desse jeito, assim tem o mesmo efeito e menos verbosidade
```suggestion
  Record<string, unknown>;
```

2024-06-21 17:47 UTC, hxsggsz commented on src/shared/infra/email/nodemailer/services/nodemailer-service.test.ts
> +import { transporter } from '@/shared/infra/email/nodemailer/config/transporter.js'; // Importe corretamente o transporter
remove esse comentario tambem, ele é redundante nesse caso

```suggestion
import { transporter } from '@/shared/infra/email/nodemailer/config/transporter.js';
```

2024-06-21 17:48 UTC, hxsggsz approved these changes

2024-06-23 01:43 UTC, k1nha commented
Não fazer merge até todas as alterações do #129 estiverem na main

2024-06-24 02:12 UTC, kvnbg commented on src/shared/infra/email/models/email-model.ts
> +  template: string;
Acho que seria interessante criar um atributo `parameters`, que ele teria todos os parametros que serão utilizados no template escolhido

2024-06-24 02:13 UTC, kvnbg requested changes
Acho que seria interessante criar um atributo parameters, que ele teria todos os parametros que serão utilizados no template escolhido

2024-06-24 23:39 UTC, matheus-webp commented on src/shared/infra/email/models/email-model.ts
> +  template: string;
export type EmailModel = {
  recipient: string;
  subject: string;
  template: string;
  parameters: Record<string, any>;
};
seria basicamente assim?

2024-06-28 01:28 UTC, closed without merging