Issue 137
devhatt/octopost-backend pull request #139
Opened 2024-06-25 23:30 UTC by jjribeiro1

Closes #137 

<details open> 
  <summary>
    <b>Feature</b>
    <p>Retorna contas associadas a um usuário </p>
  </summary>

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-06-27 02:08 UTC, kvnbg approved these changes

2024-06-29 16:17 UTC, k1nha requested changes

2024-06-29 16:17 UTC, k1nha commented on src/features/account/repositories/account-repository/account-repository.ts
> +  async findAccountsByUserId(id: string) {
não precisa colocar o async qunado a função retorna uma promise, fica meio redundante

2024-06-29 16:17 UTC, k1nha commented on src/features/user/controllers/user-controller.test.ts
> +    });
Acho que não precisa desse teste já que o `'should return accounts from user` que é um teste de sucesso  contempla esse exemplo

2024-07-16 01:08 UTC, k1nha commented
Acredito que configuração do eslint no seu vscode está mal configurada, rodei o lint local e tive alguns warnings,errors
![image](https://github.com/user-attachments/assets/afda9e75-dfa6-4068-b1f7-fffefeb4f4ee)

2024-07-18 00:28 UTC, k1nha approved these changes

2024-07-18 00:28 UTC, merged