[RELEASE] Mongodb
devhatt/octopost-backend pull request #178
Opened 2024-08-27 11:55 UTC by k1nha

* fix: ajust compose and env.example

* feat: insert new base workflows

* fix: ajust docker compose and dockerfile

* chore: remove db url from .env.example

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-09-12 20:17 UTC, Luiginicoletti approved these changes, later dismissed

2024-09-12 20:17 UTC, Luiginicoletti commented on src/teste.js
> +  console.log('FOI');
FOI
![britney-spears-reaction-gif-by-moodman](https://github.com/user-attachments/assets/5ae34568-5cdd-44c0-a2d4-1ca030921cfb)

2024-09-12 23:08 UTC, Frompaje reviewed
Depois remove o console.log

2024-09-18 01:37 UTC, SamuelMoraesF commented
O arquivo `src/teste.js` é necessário?

2024-09-18 17:37 UTC, Frompaje requested changes

2024-09-18 17:37 UTC, Frompaje commented on package.json
> +    "pisma:push": "npx primsa db push"
npx prisma db push

2024-09-23 14:23 UTC, Frompaje approved these changes

2024-09-26 02:09 UTC, davidambz approved these changes

2024-09-26 02:12 UTC, juliaam approved these changes

2024-09-26 17:12 UTC, merged