feat: test/email-service
devhatt/octopost-backend pull request #191
Opened 2024-09-12 18:44 UTC by Frompaje

Closes #190 

![image](https://github.com/user-attachments/assets/0c9c9f0c-5080-4f19-8009-9eefe57a4b4f)

2024-09-12 18:56 UTC, Luiginicoletti requested changes
Só deixar o nome do teste mais descritivo acho que já fica melhor.

![love-it-beauty-gif-by-salon-line](https://github.com/user-attachments/assets/a22ecc57-34fb-4320-8512-d285d648c2d2)

2024-09-12 18:56 UTC, Luiginicoletti commented on src/shared/infra/email/services/email-service.test.ts
> +    it('Calling the sendEmail method', async () => {
```suggestion
    it('Should call the sendEmail method and return successfully', async () => {
```

2024-09-12 19:20 UTC, juliaam approved these changes

2024-09-13 15:18 UTC, Frompaje commented on src/shared/infra/email/services/email-service.test.ts
> +    it('Calling the sendEmail method', async () => {
A segunda opção é melhor, valeu nico. A primeira é melhor botar assim

```ts 

describe("Sucess",()=>{
 describe('List', () => {
    it('Should call the sendEmail method', async () => {
      const data = {
        parameters: { name: 'John Doe' },
        recipient: 'johndoe@example.com',
        subject: 'Test Subject',
        template: 'test-template',
      };

      await emailService.sendEmail(data);

      expect(emailAdapter.sendEmail).toBeCalledWith(data);
      expect(emailAdapter.sendEmail).toHaveBeenCalledTimes(1);
    });
  })}
  ```

2024-09-13 15:20 UTC, Luiginicoletti commented on src/shared/infra/email/services/email-service.test.ts
> +    it('Calling the sendEmail method', async () => {
Amassou irmao!

2024-09-13 15:21 UTC, Luiginicoletti approved these changes
![sacha-baron-cohen-thumbs-up-gif-by-amazon-prime-video](https://github.com/user-attachments/assets/25397d84-fa18-49a7-8397-8c3781968cd8)

2024-09-13 15:22 UTC, merged