docs: atualização do endpoint de cadastro do usuário
devhatt/octopost-backend pull request #42
Opened 2024-04-29 21:10 UTC by Frompaje

❌ Antes
![image](https://github.com/devhatt/octopost-backend/assets/117830579/3ad43709-1224-4720-8b4f-df5fa53a7094)
✔️Depois
![image](https://github.com/devhatt/octopost-backend/assets/117830579/75f44eba-d490-4b36-82bf-0ec4b4b0f1b4)

2024-04-29 21:31 UTC, alvarogfn requested changes

2024-04-29 21:31 UTC, alvarogfn commented on openapi/main.yaml
> +  /api/users:
```suggestion
  /users:
```

2024-04-29 21:48 UTC, alvarogfn approved these changes

2024-04-29 22:05 UTC, k1nha approved these changes

2024-04-30 01:06 UTC, hxsggsz approved these changes

2024-04-30 01:08 UTC, aalmeida00 approved these changes

2024-04-30 01:48 UTC, k1nha approved these changes

2024-04-30 10:47 UTC, kvnbg approved these changes

2024-04-30 17:24 UTC, merged