Criar repository para consultar o usuario por id
devhatt/octopost-backend pull request #46
Opened 2024-04-30 16:11 UTC by davidspader

Closes #38

2024-04-30 16:13 UTC, davidspader commented on src/features/user/repositories/user-repository/user-repository.test.ts
> +      // eslint-disable-next-line unicorn/no-null
Aqui o eslint dizia pra usar undefined, mas dava erro no código e não consegui fazer funcionar de outro jeito

2024-04-30 16:18 UTC, davidspader commented on src/features/user/repositories/user-repository/user-repository.ts
> +      },
na issue falava sobre trazer o name também, eu fiz mas quebrou o endpoint de create que já estava feito, então eu deixei assim pra ver com vocês o que fazer, se eu devo ajustar também o que quebrar ou deixar assim

2024-04-30 17:57 UTC, alvarogfn requested changes

2024-04-30 17:57 UTC, alvarogfn commented on src/shared/test-helpers/mocks/user.mock.ts
> +      id: '00000000-0000-0000-0000-000000000000',
```suggestion
      id: faker.string.numeric(),
```

2024-04-30 17:57 UTC, alvarogfn commented on package.json
> +    "eslint-plugin-array-func": "5.0.1",
Pode remover essa library

2024-04-30 18:00 UTC, alvarogfn commented on src/features/user/repositories/user-repository/user-repository.test.ts
> +        select: {
select: expect.anything()

2024-04-30 18:00 UTC, alvarogfn commented on src/features/user/repositories/user-repository/user-repository.ts
> +      select: {
select: expect.anything()

2024-04-30 18:01 UTC, alvarogfn commented on src/features/user/repositories/user-repository/user-repository.ts
> +      },
Será necessário adicionar o name no schema do prisma e rodar uma migration. 

Aproveita e também transforma o uuid lá na tabela de user para int auto increment.

2024-04-30 21:19 UTC, aalmeida00 requested changes

2024-04-30 21:19 UTC, aalmeida00 commented on src/features/user/repositories/user-repository/user-repository.test.ts
> +    it('should return user if found', async () => {
It ... should acaba ficando redundante no ingles, pode evitar.

```suggestion
    it('return user if found', async () => {
```

2024-05-02 14:34 UTC, alvarogfn requested changes

2024-05-02 14:34 UTC, alvarogfn commented on src/features/user/repositories/user-repository/user-repository.test.ts
> +      prisma.user.findUnique.mockResolvedValue(null);
Pode remover, a regra foi desabilitada

2024-05-03 18:33 UTC, alvarogfn requested changes

2024-05-03 18:33 UTC, alvarogfn commented on src/features/user/repositories/user-repository/user-repository.ts
> +      select: expect.anything(),
Aqui não é expect, pois não é um teste.

Você deve retornar realmente os campos

```
select: {
  name: true
  ... 
} 
```

2024-05-05 14:46 UTC, alvarogfn approved these changes

2024-05-05 22:43 UTC, aalmeida00 approved these changes

2024-05-05 22:43 UTC, merged