feat: auth repository
devhatt/octopost-backend pull request #49
Opened 2024-05-02 15:36 UTC by thiagoCalazans-dev

Closes #35 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

* new folder in features called Authentication
* folder repository with Auth repository and two methods (findUserByUsername and findPasswordByUsername)
* test coverage 100%

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-05-04 17:20 UTC, alvarogfn requested changes

2024-05-04 17:20 UTC, alvarogfn commented on src/features/authentication/repositories/auth-repository/auth-repository.ts
> +    const user = await database.user.findUnique({
Você deve retornar o usuário completo com exceção da senha.

2024-05-04 17:20 UTC, alvarogfn commented on src/features/authentication/repositories/auth-repository/auth-repository.ts
> +    const user = await database.user.findUnique({
Filtra os campos, você deve retornar o usuário completo com exceção da senha.


Ajuste os testes.

2024-05-06 09:44 UTC, kvnbg approved these changes
Ótimo PR maninho

2024-05-06 19:24 UTC, k1nha requested changes

2024-05-06 19:24 UTC, k1nha commented on src/features/authentication/repositories/auth-repository/auth-repository.ts
> +};
Cria um arquivo pra essa tipagem e e coloca em PascalCase

2024-05-06 19:24 UTC, k1nha commented on src/features/authentication/repositories/auth-repository/auth-repository.ts
> +    };
não deveria rolar uma verificação se o usuário não existe aqui? isso também é valido pra qualquer find
```js
const user = ....

if (!user) return null | undefined // vale a pena discutir qual padrão vai adotar nesse retorno

//continuar o resto aqui
```

2024-05-06 19:24 UTC, k1nha commented on src/features/authentication/repositories/auth-repository/auth-repository.test.ts
é valido fazer um setup de teste nisso. Em todo caso de teste, estamos fazendo a criação de um usuário mock, não seria melhor deixar isso numa variavel e executar sempre antes dos testes?

2024-05-06 21:15 UTC, thiagoCalazans-dev commented on src/features/authentication/repositories/auth-repository/auth-repository.ts
> +    };
eu fiquei em duvida aqui, se deixa o prisma mesmo cuidar disso ou se faz a verificação e tratamento no service/use case.
no exemplo do create user não tem em nenhum momento a verificação antes de criar pra eu basear o padrao

2024-05-06 21:18 UTC, thiagoCalazans-dev commented on src/features/authentication/repositories/auth-repository/auth-repository.ts
> +};
segui o padrão do user repository que era o exemplo, que fez o tipo no mesmo arquivo.
crio o arquivo de tipo dentro da propria pasta do repository mesmo ?

2024-05-08 13:32 UTC, alvarogfn requested changes

2024-05-08 13:32 UTC, alvarogfn commented on src/features/authentication/repositories/auth-repository/auth-repository.test.ts
> +const user = UserMock.create();
Move para dentro do make sut e retorna

2024-05-08 13:32 UTC, alvarogfn commented on src/features/authentication/repositories/auth-repository/auth-repository.test.ts
> +        createdAt: new Date(),
Se vc precisa desses campos mockados, crie um novo método ou atualize o método existente da classe de mock.

2024-05-08 13:32 UTC, alvarogfn commented on src/features/authentication/repositories/auth-repository/auth-repository.ts
> +    const user = await database.user.findFirst({
Use o parâmetro select do prisma para retornar apenas os campos que você precisa.

2024-05-08 13:32 UTC, alvarogfn commented on src/features/authentication/repositories/auth-repository/auth-repository.ts
> +      where: {
Mesma coisa aqui, use o parâmetro select do prisma para retornar somente os campos que você precisa

2024-05-09 02:40 UTC, alvarogfn approved these changes

2024-05-09 19:04 UTC, k1nha approved these changes
vi os comentarios mas acho bom confirmar isso com @kvnbg

2024-05-10 11:27 UTC, alvarogfn approved these changes

2024-05-10 11:32 UTC, merged