Documentaçao do endpoint de consultar redes sociais do usuário
devhatt/octopost-backend pull request #50
Opened 2024-05-02 15:42 UTC by joaomarcelo09

2024-05-02 17:30 UTC, zoldyzdk reviewed
Coloca uma descriçãozinha nesse PR meu mano, nos outros prs tem um template pra tu se basear.

2024-05-02 23:29 UTC, joaomarcelo09 commented
> Coloca uma descriçãozinha nesse PR meu mano, nos outros prs tem um template pra tu se basear.

feito meu bom

2024-05-04 17:31 UTC, alvarogfn requested changes
Está tudo ok com o código do seu PR

Você só precisa ajustar a nomenclatura que utilizou:


Ao invés de usar 

`user-network-consult`

Substitua por

`user-network-find-all`


Consult não é um nome comumente usado e isso pode dificultar o entendimento no futuro.

2024-05-06 09:41 UTC, kvnbg approved these changes

2024-05-06 19:17 UTC, k1nha approved these changes

2024-05-07 02:46 UTC, alvarogfn approved these changes

2024-05-10 20:48 UTC, merged