feat: add getAccounts method to user repository
devhatt/octopost-backend pull request #56
Opened 2024-05-06 20:39 UTC by davidspader

Closes #40 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

criado método getAccounts() e testes, que recebe o id do usuário e retorna todas as contas de rede sociais do usuário no user repository

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-05-07 19:32 UTC, davidspader commented
a issue diz pra fazer no UserRepository, não seria melhor criar um account repository?

2024-05-08 16:29 UTC, kvnbg commented
> a issue diz pra fazer no UserRepository, não seria melhor criar um account repository?

Sim. A issue está desatualizada, seria ideal criar uma features/accounts e ter o repository lá que retorna essas Accounts. Nessa mesma feature iremos fazer a parte de integração com as redes sociais futuramente

2024-05-11 02:25 UTC, kvnbg requested changes

2024-05-11 02:25 UTC, kvnbg commented on src/features/account/repositories/account-repository/account-repository.ts
> +    return userAccounts || [];
Quando o find não encontra registros ele já retorna um array vazio, acho que ai já pode retornar direto o `userAccounts`
```suggestion
    return userAccounts;
```

Acho que ajustando isso, deve resolver o alerta do coverage que gerou no build, que não cobriu 100% do código.

2024-05-13 15:25 UTC, kvnbg approved these changes

2024-05-13 17:50 UTC, k1nha requested changes

2024-05-13 17:50 UTC, k1nha commented on src/features/account/repositories/account-repository/account-repository.ts
> +import { database } from '@/shared/infra/database/database.js';
```suggestion
import { database } from '@/shared/infra/database/database';
```

2024-05-13 17:50 UTC, k1nha commented on src/shared/test-helpers/mocks/account.mock.ts
> +    return {
```ts
type Account = {
  avatarUrl: string;
  id: string;
  socialMediaId: number;
  userId: string;
}

export class AccountMock {
  public static create(override?: Account) {
    return {
      avatarUrl: faker.image.avatar(),
      id: faker.string.numeric(),
      socialMediaId: faker.number.int(),
      userId: faker.string.numeric(),
      ...override
    };
  }
}
```
**esse comentário não precisa ser uma mudança** mas seria bom a gnt criar mocks recebendo o próprio account pra reutilizar em alguns testes

2024-05-13 18:24 UTC, k1nha approved these changes

2024-05-13 18:39 UTC, merged