feat: add getUser controller
devhatt/octopost-backend pull request #57
Opened 2024-05-08 01:37 UTC by nathalia-84

Closes #36 

<details open> 
  <summary>
    <b>criado controller getUser, que recebe o id do usuário por meio de query parameter e retorna no corpo da resposta todas as informações do usuário (id, nome, email, username)</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ x ] Issue linked
- [ x ] Build working correctly
- [ x ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-05-08 14:31 UTC, alvarogfn requested changes
Deixei alguns comentários de ajuste.

Também é necessário seguir a mesma nomenclatura definida na documentação.


Então o `get-user` se tornaria `user-find-by-id`

2024-05-08 14:31 UTC, alvarogfn commented on src/features/user/routes/user-routes.ts
>    prefix: 'user',
Ajustar prefixo para users

2024-05-08 14:31 UTC, alvarogfn commented on src/features/user/validators/user-create-schema.ts
> +export const userGetSchema = Joi.object({
Mover para outro arquivo de schema

2024-05-08 14:31 UTC, alvarogfn commented on src/features/user/controllers/user-controller.ts
> +      this.validator.validate(userGetSchema, {
Valide o path inteiro:

{
  path: req.path
  body: req.body
  query: req.query
}

2024-05-08 14:31 UTC, alvarogfn commented on src/features/user/controllers/user-controller.ts
> +      this.validator.validate(userGetSchema, {
Valide o path inteiro:

{
  path: req.path
  body: req.body
  query: req.query
}

2024-05-08 14:31 UTC, alvarogfn commented on src/features/user/controllers/user-controller.ts
> +    private userRepository: UserRepository
Você não deve chamar o UserRepository dentro do controller.

2024-05-08 14:31 UTC, alvarogfn commented on src/features/user/controllers/user-controller.ts
> +      let user = await this.userRepository.findById(userId);
Remover essa chamada pro userRepository

2024-05-08 14:31 UTC, alvarogfn commented on src/features/user/routes/user-controller-factory.ts
> +    userRepository
Remover userRepository

2024-05-08 14:31 UTC, alvarogfn commented on src/features/user/validators/user-create-schema.ts
> +  id: Joi.string().required().pattern(new RegExp('^\\d+$')),
Joi.string().guid()

2024-05-08 14:49 UTC, nathalia-84 commented on src/features/user/controllers/user-controller.ts
> +      let user = await this.userRepository.findById(userId);
Olá, então como farei para ter acesso ao findById ?

2024-05-11 02:35 UTC, kvnbg approved these changes

2024-05-14 15:23 UTC, hxsggsz approved these changes

2024-05-16 01:59 UTC, kvnbg approved these changes

2024-05-20 20:23 UTC, merged