[Email] - Criação de módulo que controle o envio de emails
devhatt/octopost-backend pull request #65
Opened 2024-05-09 22:47 UTC by yan-pi

Closes #27 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criação de um módulo agnóstico de envio de email dentro da src/shared/infra/email, ele deverá expor métodos responsáveis pelo envio de um email a partir de um template pronto.
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Não rolaram testes dessa vez. A issue é sobre criar uma interface de envio de email, mas como ela ainda não tem uma funcionalidade propriamente dito, achei melhor não forçar a barra e apaguei o que tinha feito. 

Conversei com o Kinha e o Pilu pois estava com duvida se era necessário e era problema de skill issue minha. Até tentei criar alguns testes só pra ver se a função estava sendo chamada, mas não tinha muito sentido sem uma funcionalidade definida.
</details>

2024-05-11 02:39 UTC, kvnbg approved these changes

2024-05-13 18:03 UTC, k1nha requested changes

2024-05-13 18:03 UTC, k1nha commented on src/shared/infra/email/services/email-service.ts
> +import type { EmailProvider } from '@/shared/infra/email/providers/email-provider.js';
```suggestion
import type { EmailProvider } from '@/shared/infra/email/providers/email-provider';
```

2024-05-13 18:03 UTC, k1nha commented on src/shared/infra/email/services/email-service.ts
> +  }
```suggestion
  constructor(private readonly emailProvider: EmailProvider) { }
```
bom utilizar a syntax sugar do ts

2024-05-15 15:23 UTC, yan-pi commented on src/shared/infra/email/services/email-service.ts
> +  }
done [938c74e]

2024-05-16 01:50 UTC, kvnbg requested changes

2024-05-16 01:50 UTC, kvnbg commented on src/shared/infra/email/providers/email-provider.ts
> +export interface EmailProvider {
Man, sei que já aprovei teu PR. Mas dando uma revisada de novo aqui. Acho seria interessante mudar o nome dessa interface e da pasta para adapters, ai os usecase/service utilizariam essa interface, e nos factory iriamos injetar a implementação dela

```suggestion
export interface EmailAdapter {
```

2024-05-16 01:50 UTC, kvnbg commented on src/shared/infra/email/services/email-service.ts
> +export class EmailService {
Nessa classe teria que fazer a implementaçao do EmailAdapter, meio que ficaria uma NodemailerAdapter implements EmailAdapter, se liga? 

Vou criar uma nova task pra fazer a implementação do carinha de email, provavelmente vai acabar sendo o nodemailer, mas vou consultar os universitários.

2024-05-20 22:14 UTC, kvnbg approved these changes

2024-05-20 22:17 UTC, k1nha approved these changes

2024-05-20 22:24 UTC, merged