Add dockerfile and docker compose build
devhatt/octopost-backend pull request #66
Opened 2024-05-10 22:47 UTC by PiluVitu

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criação do docker compose para buildar o projeto e subir em conjunto com o banco de dados, também foi criado um dockerfile que contem somente a aplicação buildada para facilitar a versatilidade de deploy futuramente 

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/devhatt/octopost-backend/assets/69992923/f1d0ad37-55bd-4d3b-8449-e88da222982e)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-05-10 23:21 UTC, k1nha commented on prisma/schema.prisma
qual motivo disso aqui?

2024-05-10 23:25 UTC, PiluVitu commented on prisma/schema.prisma
Ele precisa disso para rodar o `prima generate` dentro do container, a sugestão foi feita pelo proprio prisma

2024-05-10 23:54 UTC, alvarogfn requested changes

2024-05-10 23:54 UTC, alvarogfn commented on .dockerignore
> +.github
eof

2024-05-10 23:54 UTC, alvarogfn commented on build.Dockerfile
> +CMD ["pnpm", "run", "start"]
mais um eof

2024-05-13 17:56 UTC, k1nha approved these changes

2024-05-20 22:13 UTC, kvnbg approved these changes

2024-05-31 19:02 UTC, merged