Issue 24
devhatt/octopost-backend pull request #67
Opened 2024-05-11 20:42 UTC by Clerijr

Closes #24 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Adiciona validação de username e email ao criar um novo usuário

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

2024-05-13 15:36 UTC, alvarogfn requested changes

2024-05-13 15:36 UTC, alvarogfn commented on src/features/user/routes/user-controller-factory.ts
> +  const userService = new UserCreateService(userRepository);
const userServiceCreate = new UserCreateService(userRepository);

2024-05-13 15:36 UTC, alvarogfn commented on src/features/user/services/user-create-service.test.ts
> +    findByUsernameOrEmail(): any {
Aqui você vai retornar de fato o usuário, pois é um caso de default do repository.

2024-05-14 15:12 UTC, hxsggsz requested changes

2024-05-14 15:12 UTC, hxsggsz commented on src/features/user/services/user-create-service.test.ts
> +      repeatPassword: 'valid_password',
senti que ficou faltou um teste pro case da senha ser diferente da verificação de senha

2024-05-22 19:55 UTC, hxsggsz approved these changes

2024-05-24 21:16 UTC, merged