feat: create and test user findById service
devhatt/octopost-backend pull request #75
Opened 2024-05-15 14:48 UTC by davidspader

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Create and test user findById service

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-05-18 14:08 UTC, zoldyzdk requested changes
Só uma paradas do prettier, vê o comando que faz um fix no package.json e pronto.

![image](https://github.com/devhatt/octopost-backend/assets/90076846/df3d6dfe-d59b-4cf8-94d5-b7c2226ebc01)

2024-05-20 11:59 UTC, zoldyzdk approved these changes

2024-05-20 22:11 UTC, kvnbg commented on src/features/user/services/user-create-service.test.ts
> +      throw new Error('Method not implemented. ' + id);
Acredito que ele implementou o metodo voltando erro apenas para que a implementação atenda a interface. Como ai se trata do test de criar o usuário, na teoria não deveria ta testando esse findById. Da mesma forma que o caso contrário acontece no teste que ele fez do findById lançando o erro no createUser

2024-05-20 22:13 UTC, davidspader commented on src/features/user/services/user-create-service.test.ts
> +      throw new Error('Method not implemented. ' + id);
Foi isso mesmo

2024-05-21 00:06 UTC, zoldyzdk approved these changes

2024-05-22 19:12 UTC, k1nha approved these changes

2024-05-22 22:50 UTC, closed without merging