feat: add service to consult social media accounts per user
devhatt/octopost-backend pull request #88
Opened 2024-05-22 06:25 UTC by matheus-webp

Closes #41 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

add service to consult social media accounts per user

</details>
<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [X] Issue linked
- [X] Build working correctly
- [X] Tests created
</details>

2024-05-24 02:28 UTC, kvnbg requested changes
No geral, o PR tá show. Só preciso que faça uma coisa. Você acabou criando tudo no `features/user`, o ideal seria criar essa service no `features/account` pq o objeto do negócio que estamos trabalhando nesse caso é o Account e não mais o User. O user.id que precisa aqui ele tá funcionando mais como um filtro aqui.

2024-05-24 02:28 UTC, kvnbg commented on src/features/user/services/user-service.ts
> +    await this.accountRepository.getAccounts(id);
ficou faltando só a `return` para poder devolver o resultado para quem tá chamando a função

2024-05-24 02:28 UTC, kvnbg commented on src/features/user/services/user-service.ts
> +export class UserService implements Service<UserModel> {
É uma boa colocar o nome do Service mais especifico indicando o que ele faz. 
```suggestion
export class GetUserAccountsService implements Service<UserModel> {
```

2024-05-24 13:45 UTC, hxsggsz requested changes

2024-05-24 13:45 UTC, hxsggsz commented on src/features/account/services/get-user-accounts-service.ts
> +      throw new Error('User not found');
cria um custom error em shared igual tem o `validation-error` e usa aqui

2024-05-24 13:45 UTC, hxsggsz commented on src/features/account/services/get-user-accounts-service.test.ts
> +  it('should call userRepository.findById with correct id', async () => {
evita o uso repetido de should nos seus testes, isso deixa eles pouco semânticos
```suggestion
  it('calls userRepository.findById with correct id', async () => {
```

2024-05-24 21:48 UTC, k1nha commented on src/features/account/services/get-user-accounts-service.ts
> +    return await this.accountRepository.getAccounts(id);
não precisaria desse await aqui, mas blz

2024-05-24 21:51 UTC, k1nha approved these changes

2024-05-24 21:53 UTC, hxsggsz approved these changes

2024-05-25 00:09 UTC, kvnbg approved these changes

2024-05-25 00:10 UTC, merged