Yuri silveiraa/issue 26
devhatt/octopost-backend pull request #94
Opened 2024-05-23 16:06 UTC by yuri-silveiraa

Closes

<details open> 
  <summary>
    <b>Feature</b>
Criação da classe JWTHelper junto do middleware AuthenticationJWT
  </summary>

A class JWTHelper tem o intuito de fornecer a criação de um token a partir de um payload passado, de recriar um token a partir de um token valido e também de a partir de um token valido trazer o seu payload.
O middleware AuthenticationJWT tem como função verificar se o token é valido, e se o usuario daquele token é um usuário valido também. 

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-05-24 13:30 UTC, hxsggsz commented
preciso que você linque o id da sua issue no seu pr e que atualize a sua branch

2024-05-24 13:36 UTC, hxsggsz requested changes

2024-05-24 13:36 UTC, hxsggsz commented on src/middlewares/auth/auth-jwt-factory.ts
> +  const jwt = new JWTHelper(process.env.SECRET_KEY as string);
em `config` tem um arquivo de configuração de envs, ve como que ele funciona e usa aqui

2024-05-24 13:36 UTC, hxsggsz commented on src/middlewares/auth/auth-jwt.test.ts
> +import { beforeEach, describe, expect, it } from 'vitest';
isso aqui você tem acesso global, não precisa importar
```suggestion

```

2024-05-31 19:06 UTC, k1nha commented on src/shared/infra/jwt/jwt.ts
> +  }
não precisaria desses try catch

2024-05-31 19:26 UTC, k1nha commented on src/middlewares/auth/auth-jwt.test.ts
essa implementação foi testada em algum controller?

2024-06-01 10:31 UTC, yuri-silveiraa commented on src/middlewares/auth/auth-jwt.test.ts
não, quando tava fazendo não tinha nenhum controller que desse pra eu testar

2024-06-01 10:32 UTC, yuri-silveiraa commented on package.json
> +    "joi": "17.13.0",
não sei, alias nem sei pq atualizou, não mexi em nada referente ao joi

2024-06-03 16:56 UTC, yuri-silveiraa commented on src/shared/infra/jwt/jwt.ts
> +  }
porque não? seria melhor usar early return?

2024-06-03 17:25 UTC, kvnbg commented on src/shared/infra/jwt/jwt.ts
> +  }
Também não entendi o motivo de não usar @k1nha. Tem em mente deixar pra quem tá chamando esses métodos fazer o tratamento das exceções?

2024-06-05 18:32 UTC, hxsggsz commented on src/shared/infra/jwt/jwt.ts
> +  }
acho que nessas duas situações ele nunca vai cair no catch

2024-06-06 19:45 UTC, k1nha commented on src/shared/infra/jwt/jwt.ts
> +  }
> acho que nessas duas situações ele nunca vai cair no catch

exatamente

acho que a gente consegue deixar esse codigo mais enxuto

2024-06-09 10:50 UTC, kvnbg commented on src/shared/infra/jwt/jwt.ts
> +  }
Ah pô, saquei o b.o ai. @yuri-silveiraa, a questão é a seguinte: 

Os métodos `parseToken` e `createToken`, nenhum tá lançando exceção em caso de problema. Então o bloco de `try...catch` que você colocou no `refreshToken` nunca irá cair no catch, pois não tem possíveis exceções dentro do bloco `try` que precisaria de tratamento.

Então, no `refreshToken` você poderia deixar apenas o código que está dentro do `try`

2024-06-10 19:41 UTC, hxsggsz approved these changes

2024-06-11 13:00 UTC, k1nha approved these changes

2024-06-12 12:04 UTC, merged