Issue 62
devhatt/octopost-backend pull request #95
Opened 2024-05-24 21:21 UTC by muritadb

Closes #62 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Account Repository

</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>

Criado repository para buscar redes sociais do usuarios por ID
</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

</details>

2024-05-24 21:39 UTC, hxsggsz requested changes

2024-05-24 21:39 UTC, hxsggsz commented on prisma/schema.prisma
> +  updatedAt     DateTime @default(now()) @updatedAt @map("updated_at")
se eu nao me mengano nao precisa do `@default` no updatedAt, o `@updatedAt` ja lida isso por você

2024-05-24 21:39 UTC, hxsggsz commented on src/features/user/repositories/account-repository/account-repository.ts
> +    return database.account.create({
```suggestion
    return await database.account.create({
```

2024-05-24 21:39 UTC, hxsggsz commented on src/features/user/repositories/account-repository/account-repository.ts
> +    return socialMidias;
aqui voce ta atribuindo  a uma variável e depois retornando ela mas em cima voce ta retornando a operação direto, da uma olhada no projeto e ve qual é o padrão pra seguir. Se nao tiver um padrão vamos seguir com o padrão que voce fez aqui

2024-05-30 17:34 UTC, muritadb commented on src/features/user/repositories/account-repository/account-repository.ts
> +    return database.account.create({
Entendi, como a função é async, deve retornar com await .

2024-05-30 17:37 UTC, muritadb commented on src/features/user/repositories/account-repository/account-repository.ts
> +    return socialMidias;
@hxsggsz o padrão do user repository com o qual eu segui é assim tambem, por isso fiz dessa forma.

2024-05-30 17:41 UTC, muritadb commented on prisma/schema.prisma
> +  updatedAt     DateTime @default(now()) @updatedAt @map("updated_at")
Então não precisa do @default ?

2024-05-31 19:13 UTC, k1nha commented on src/features/user/repositories/account-repository/account-repository.ts
> +    return database.account.create({
nao precisaria nem do async, nem do await
só retornar a função que funcionaria

2024-06-05 18:35 UTC, hxsggsz requested changes

2024-06-05 18:35 UTC, hxsggsz commented on src/features/user/repositories/account-repository/account-repository.ts
> +    return socialMidias;
então segue com esse padrão nos dois métodos dessa classe

2024-06-06 15:39 UTC, muritadb commented on src/features/user/repositories/account-repository/todos.md
deletado!

2024-06-06 15:42 UTC, muritadb commented on prisma/schema.prisma
> +  updatedAt     DateTime @default(now()) @updatedAt @map("updated_at")
removido!!

2024-06-07 12:14 UTC, hxsggsz approved these changes

2024-06-09 10:42 UTC, kvnbg requested changes
Só esse arquivo todos.md que precisa remover

2024-06-09 10:42 UTC, kvnbg commented on src/features/user/repositories/account-repository/todos.md
@muritadb remove esse arquivo por favor

2024-06-11 17:18 UTC, hxsggsz commented on package.json
> +}
EOF

adiciona um espaço em branco no fim desse arquivo

2024-06-11 17:18 UTC, hxsggsz approved these changes

2024-06-11 22:56 UTC, muritadb commented on package.json
> +}
Corrigido

![image](https://github.com/devhatt/octopost-backend/assets/19556950/328783b3-f7bc-42db-9070-3128efb9ac3e)

2024-06-12 00:48 UTC, kvnbg approved these changes

2024-06-12 00:49 UTC, merged